services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=statutis
    volumes:
      - postgress:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgress: 